services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.git
      - ./backend/firebaseservicekey.json:/app/firebaseservicekey.json

# MongoDB Atlas is used - configure MONGO_URI in .env file with your Atlas connection string
